/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import jakarta.xml.ws.Endpoint;
// local imports
import org.example.service.BantuLodgeService;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String url = "http://localhost:8086/BantuLodgeService";
        Endpoint.publish(url, new BantuLodgeService());
        System.out.println("BantuLodge SOAP servive started at " + url);
    }
}
